### ISSUE TITLE
Automatically make use of .gnu_debuglink where possible

### ISSUE THREAD

**Issue by wcohen** [pmachata/dwgrep#37]
It would be convenient when dwgrep didn't find the debug_* sections but did find a .gnu_debuglink section it would make use of the .gnu_debuglink and find the separate debug info file like gdb and tools do.  This would make it much easier to use dwgrep on binaries in Linux distributions such as Fedora.

**Comment by wcohen** [comment]
I misspoke.  It looks like this is already implemented in dwgrep:

$ dwgrep 'entry  @AT_location'  /usr/bin/cp|more
dwgrep: /usr/bin/cp: No DWARF information found
$ sudo dnf debuginfo-install coreutils
...
0..0xffffffffffffffff:0 addr <26112>
0..0xffffffffffffffff:0 addr <26111>
0..0xffffffffffffffff:0 addr <26110>
0..0xffffffffffffffff:0 addr <257c0>
0..0xffffffffffffffff:0 addr <1c460>
0..0xffffffffffffffff:0 addr <257a0>
0..0xffffffffffffffff:0 addr <1c450>
0..0xffffffffffffffff:0 addr <253e0>
0x5310..0x5335:0 reg5
0x5335..0x555d:0 reg12

**Comment by pmachata** [comment]
Yep, dwgrep is using elfutils under the hood and it should just transparently work.

On April 14, 2020 1:53:50 AM GMT+02:00, William Cohen <notifications@github.com> wrote:
>I misspoke.  It looks like this is already implemented in dwgrep:
>
>$ dwgrep 'entry  @AT_location'  /usr/bin/cp|more
>dwgrep: /usr/bin/cp: No DWARF information found
>$ sudo dnf debuginfo-install coreutils
>...
>0..0xffffffffffffffff:0 addr <26112>
>0..0xffffffffffffffff:0 addr <26111>
>0..0xffffffffffffffff:0 addr <26110>
>0..0xffffffffffffffff:0 addr <257c0>
>0..0xffffffffffffffff:0 addr <1c460>
>0..0xffffffffffffffff:0 addr <257a0>
>0..0xffffffffffffffff:0 addr <1c450>
>0..0xffffffffffffffff:0 addr <253e0>
>0x5310..0x5335:0 reg5
>0x5335..0x555d:0 reg12
>
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/pmachata/dwgrep/issues/37#issuecomment-613152482

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.
